function [AUC]= calc_auc_fast(...
       Quantity_of_peaks_of_patient,...
       Quantity_of_peaks_of_control,... 
       plot_bar,...
       plot_AUC_histograms,...
       plot_ROC_TPR_FRR,...
       pTotalA,...
	   MinFreq,...
	MaxFreq,...
	MinAmpl,... 
	MaxAmpl,...
	MinDurat,...
	MaxDurat,...
    MinDurat_in_Periods,...
	MaxDurat_in_Periods,...
	MinBandwidth,...
	MaxBandwidth,...
	MinPhase,...
	MaxPhase,...
    MinTime,...
	MaxTime,...
	MinPsi0,...
	MaxPsi0);

[FontName,FontSize,FontWeight]= fontAttr();

if plot_bar, 

GlobalMin= min([...
	min(Quantity_of_peaks_of_control),...
	min(Quantity_of_peaks_of_patient)]);
GlobalMax= max([...
	max(Quantity_of_peaks_of_control),...
	max(Quantity_of_peaks_of_patient)]);

NumberOfBins=10;

Step= (GlobalMax - GlobalMin) / NumberOfBins;
...x= [GlobalMin + Step / 2 : Step : GlobalMax - Step / 2];
x= [GlobalMin : Step : GlobalMax];

if GlobalMin >= GlobalMax,
	x= [GlobalMin - 1, GlobalMin, GlobalMin + 1]; 
end;

[y1,xout]= hist(Quantity_of_peaks_of_control,x);
[y2,xout]= hist(Quantity_of_peaks_of_patient,x);

y= [y1;y2]';
Fig=123;
figure(Fig);
set(figure(Fig),'Color',[1,1,1]);
set(figure(Fig),'NumberTitle','off');
set(figure(Fig),'name',' ');
set(gca,'FontSize',FontSize);
grid('on');
bar(xout,y);

colormap('cool');

xlabel([...
	'Quantity of wave trains in a person per second, ',...
	'p<=',num2str(pTotalA),' ',...
	...exclamation_marks...
	],...
	...'color', XColor,...
	'FontName',FontName,...
	'FontSize',FontSize,...
	'FontWeight',FontWeight,...
	'Interpreter','none'); % не включать TEX

ylabel(...
	'Number of persons',...
	'FontName',FontName,...
	'FontSize',FontSize,...
	'FontWeight',FontWeight,...
	'Interpreter','none'); % не включать TEX

legend({'Control','Patients'});

Text= [...
 	'MinFreq: ',num2str(MinFreq),' [Hz]',char(10),...
 	'MaxFreq: ',num2str(MaxFreq),' [Hz]',char(10),...
	'MinAmpl: ',num2str(MinAmpl),' [mkV]',char(10),...
	'MaxAmpl: ',num2str(MaxAmpl),' [mkV]',char(10),...
	'MinDurat_in_Periods: ',num2str(MinDurat_in_Periods),' [Periods]',char(10),...
	'MaxDurat_in_Periods: ',num2str(MaxDurat_in_Periods),' [Periods]',char(10),...
	'MinBandwidth: ',num2str(MinBandwidth),' [Hz]',char(10),...
	'MaxBandwidth: ',num2str(MaxBandwidth),' [Hz]',char(10),...
	'MinPhase: ',num2str(MinPhase),' [rad]',char(10),...
	'MaxPhase: ',num2str(MaxPhase),' [rad]',char(10),...
    'MinTime: ',num2str(MinTime),' [s]',char(10),...
	'MaxTime: ',num2str(MaxTime),' [s]',char(10),...
	'MinPsi0: ',num2str(MinPsi0),' [rad]',char(10),...
	'MaxPsi0: ',num2str(MaxPsi0),' [rad]',char(10)];

TextX= (min(x) + max(x)) / 2;
TextY= max([max(y1),max(y2)]);

text(...
	TextX,...
	TextY,...
	Text,...
	'Color','k',...
	'Margin',5,...
	'BackgroundColor','y',...
	'HorizontalAlignment','center',...
	'VerticalAlignment','top',...
	'FontName',FontName,...
	'FontSize',12,...
	'FontWeight',FontWeight,...
	'Interpreter','none');

end;

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

MIN1= min(Quantity_of_peaks_of_patient);
MIN2= min(Quantity_of_peaks_of_control);
MIN3= min(MIN1,MIN2);

MAX1= max(Quantity_of_peaks_of_patient);
MAX2= max(Quantity_of_peaks_of_control);
MAX3= max(MAX1,MAX2);

ThresholdStep= (MAX3-MIN3) / 1000;

if ThresholdStep <= 0,
	ThresholdStep= 0.01;
end;

ThresholdArray= [MIN3-ThresholdStep:ThresholdStep:MAX3+ThresholdStep];
LengthOfThresholdArray= length(ThresholdArray);

TP_array= zeros(1,LengthOfThresholdArray);
FP_array= zeros(1,LengthOfThresholdArray);
TN_array= zeros(1,LengthOfThresholdArray);
FN_array= zeros(1,LengthOfThresholdArray);

counter= 0;

for k=1:LengthOfThresholdArray,
	counter= counter + 1;
	for i=1:length(Quantity_of_peaks_of_patient),
		if	Quantity_of_peaks_of_patient(i) > ...
			ThresholdArray(counter);
			TP_array(counter)= TP_array(counter) + 1;
		else
			FN_array(counter)= FN_array(counter) + 1;
		end;
	end;
	for z=1:length(Quantity_of_peaks_of_control),
		if	Quantity_of_peaks_of_control(z) > ...
			ThresholdArray(counter);
			FP_array(counter)= FP_array(counter) + 1;
		else
			TN_array(counter)= TN_array(counter) + 1;
		end;
	end;
end;

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
if plot_AUC_histograms,

figure(100001);
hold('on');
plot(ThresholdArray, TP_array, 'r');
plot(ThresholdArray, TN_array, 'b');
plot(ThresholdArray, FP_array, 'm');
plot(ThresholdArray, FN_array, 'g');
legend({'TP','TN', 'FP', 'FN'});
xlabel(...
	'Threshold of the Recognition Procedure',...
	'FontSize',FontSize); 
ylabel(...
	'Recognition Procedure Characteristics',...
	'FontSize',FontSize);

end;

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

% Rate of positive predictions
RPP= (TP_array+FP_array)./(TP_array+FN_array+FP_array+TN_array);
% Rate of negative predictions
RNP= (TN_array+FN_array)./(TP_array+FN_array+FP_array+TN_array);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

if plot_AUC_histograms,
    
figure(100002);
hold('on');
plot(ThresholdArray, RPP, 'r');
plot(ThresholdArray, RNP, 'b');
legend({'RPP','RNP'});
xlabel(...
	'Threshold of the Recognition Procedure',...
	'FontSize',FontSize); 
ylabel(...
	'Recognition Procedure Characteristics',...
	'FontSize',FontSize);
end;

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

% Accuracy
accu= (TP_array+TN_array)./(TP_array+FN_array+FP_array+TN_array);
% True positive rate, sensitivity, recall
TPR_sens_reca= TP_array./(TP_array+FN_array);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

if plot_AUC_histograms,

figure(100003);
hold('on');
plot(ThresholdArray, accu, 'r');
plot(ThresholdArray, TPR_sens_reca, 'b');
legend({'accu','TPR_sens_reca'});
xlabel(...
	'Threshold of the Recognition Procedure',...
	'FontSize',FontSize); 
ylabel(...
	'Recognition Procedure Characteristics',...
	'FontSize',FontSize);
end;

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% False negative rate, miss
FNR_miss= FN_array./(TP_array+FN_array);
% False positive rate, fallout
FPR_fall= FP_array./(TN_array+FP_array);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

AUC= abs(trapz(FPR_fall,TPR_sens_reca)); % !!!!!!!!!!!!!!!!!
%AUC
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

if plot_AUC_histograms, 
    
figure(100004);
hold('on');
plot(ThresholdArray, FNR_miss, 'r');
plot(ThresholdArray, FPR_fall, 'b');
legend({'FNR_miss','FPR_fall'});
xlabel(...
	'Threshold of the Recognition Procedure',...
	'FontSize',FontSize); 
ylabel(...
	'Recognition Procedure Characteristics',...
	'FontSize',FontSize);
end;

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

% True negative rate, specificity
TNR_spec= TN_array./(TN_array+FP_array);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

if plot_AUC_histograms,

figure(100005);
hold('on');
plot(ThresholdArray, TNR_spec, 'r');
legend({'TNR_spec'});
xlabel(...
	'Threshold of the Recognition Procedure',...
	'FontSize',FontSize); 
ylabel(...
	'Recognition Procedure Characteristics',...
	'FontSize',FontSize);
end;

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

% Positive predictive value, precision
PPV_prec= TP_array./(TP_array+FP_array);
% Negative predictive value
NPV= TN_array./(TN_array+FN_array);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

if plot_AUC_histograms,

figure(100006);
hold('on');
plot(ThresholdArray, PPV_prec, 'r');
plot(ThresholdArray, NPV, 'b');
legend({'PPV_prec','NPV'});
xlabel(...
	'Threshold of the Recognition Procedure',...
	'FontSize',FontSize); 
ylabel(...
	'Recognition Procedure Characteristics',...
	'FontSize',FontSize);
end;

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

if plot_ROC_TPR_FRR,
        
figure(100007);
hold('on');

plot(FPR_fall, TPR_sens_reca, 'Color', ColorOfROC);

legend(...
	Legend2,...
	'Location', 'SouthEast',...
	'FontName',FontName,...
	'FontSize',FontSize-7,...
	'FontWeight',FontWeight,...
	'Interpreter','none'...
 	);

xlabel(...
	'False Positive Rate (1-Specificity)',...
	'FontName',FontName,...
	'FontSize',FontSize,...
	'FontWeight',FontWeight,...
	'Interpreter','tex');
ylabel(...
	'True Positive Rate (Sensitivity)',...
	'FontName',FontName,...
	'FontSize',FontSize,...
	'FontWeight',FontWeight,...
	'Interpreter','tex');
title(...
	WindowTitle,...
	'Color','k',...
	'FontName',FontName,...
	'FontSize',FontSize-12,...
	'FontWeight',FontWeight,...
	'HorizontalAlignment','center',...
	'Interpreter','none'...
 	);
set(gca,'FontName',FontName);
set(gca,'FontSize',FontSize);
set(gca,'FontWeight',FontWeight);

end;

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%