%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% (c) 2014 Olga S. Sushkova, Alexei A. Morozov                        %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

function...
[...
SelectedVector...
]= notch_filtering(...
	Frequency,...
	SelectedVector,...
	SamplingRate,...
	Q);

wo= Frequency / (SamplingRate / 2);
bw= wo / Q;

disp([	'A second-order IIR notch filter is used: f0= ',...
	num2str(Frequency),' Hz, ',...
	'Q= ',...
	num2str(Q),', '...
	'order: 2*2=4.'...
	]);

% Make order 2 bandstop digital filter:

[b,a]= iirnotch(wo,bw);

SelectedVector= filtfilt(b,a,SelectedVector);
