%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% (c) 2015 Olga S. Sushkova, Alexei A. Morozov                        %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

function ...
[...
AUC...
]= plot_hist_quantity_of_peaks_patients_and_control_fast(...
	Quantity_of_peaks_of_patient,...
	Quantity_of_peaks_of_control,...
	MinFreq,...
	MaxFreq,...
	MinAmpl,... 
	MaxAmpl,...
	MinDurat,...
	MaxDurat,...
    MinDurat_in_Periods,...
	MaxDurat_in_Periods,...
	MinBandwidth,...
	MaxBandwidth,...
	MinPhase,...
	MaxPhase,...
    MinTime,...
	MaxTime,...
	MinPsi0,...
	MaxPsi0,...
	Legend1,...
	plot_bar,...
	plot_AUC_histograms,...
	plot_ROC_TPR_FRR,...
    AlphaLevel,...
    DarkGreen,...
    calc_hole,...
    count);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

NumberOfBins= 10;

[FontName,FontSize,FontWeight]= fontAttr();

ColorRed= [1, 0, 0];
ColorGreen= [0, 1, 0];
ColorBlue= [0, 0, 1];
ColorCyan= [0, 1, 1];
ColorBlack= [0, 0, 0];
ColorWhite= [0.5, 0.5, 0.5];
ColorYellow= [1, 1, 0];
ColorMagenta= [1, 0, 1];

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
% (+) FolderNamePatients - Название группы пациентов
% (+) FolderNameControl - Название группы контроля
% (+) TremorSide - На какой стороне тела тремор
% (+) StatusOfHemisphereOrHand - Статус части тела, которую исследуем
% (+) SelectedHandOrHemisphere - Выбранный для анализа электрод
% (+) Fig - Номер рисунка, для разных каналов разный цвет
% (+) ColorOfROC - Цвет графика
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Fig - Номер рисунка, для разных каналов разный цвет
% ColorOfROC - Цвет графика

ColorRed= [1, 0, 0];
ColorGreen= [0, 1, 0];
ColorBlue= [0, 0, 1];
ColorCyan= [0, 1, 1];
ColorBlack= [0, 0, 0];
ColorWhite= [0.5, 0.5, 0.5];
ColorYellow= [1, 1, 0];
ColorMagenta= [1, 0, 1];

Colors=	{	ColorRed,...
		ColorGreen,...
		ColorBlue,...
		ColorCyan,...
		ColorBlack,...
		ColorWhite,...
		ColorYellow,...
		ColorMagenta...
		};

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

MedianControl= median(Quantity_of_peaks_of_control);
MedianPatients= median(Quantity_of_peaks_of_patient);

pTotalA= ranksum(...
    Quantity_of_peaks_of_patient,...
    Quantity_of_peaks_of_control);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

if calc_hole== true,
    
    if pTotalA > AlphaLevel,
        	AUC= NaN;
    else      
    [AUC]= calc_auc_fast_phase_time_psi0(...
        Quantity_of_peaks_of_patient,...
        Quantity_of_peaks_of_control,...
        plot_bar,...
        plot_AUC_histograms,...
        plot_ROC_TPR_FRR,...
		pTotalA,...
		MinFreq,...
	MaxFreq,...
	MinAmpl,... 
	MaxAmpl,...
	MinDurat,...
	MaxDurat,...
    MinDurat_in_Periods,...
	MaxDurat_in_Periods,...
	MinBandwidth,...
	MaxBandwidth,...
	MinPhase,...
	MaxPhase,...
	MinTime,...
	MaxTime,...
	MinPsi0,...
	MaxPsi0);
    end;
else
   [AUC]= calc_auc_fast_phase_time_psi0(...
       Quantity_of_peaks_of_patient,...
       Quantity_of_peaks_of_control,...
       plot_bar,...
       plot_AUC_histograms,...
       plot_ROC_TPR_FRR,...
	   pTotalA,...
	   MinFreq,...
	MaxFreq,...
	MinAmpl,... 
	MaxAmpl,...
	MinDurat,...
	MaxDurat,...
    MinDurat_in_Periods,...
	MaxDurat_in_Periods,...
	MinBandwidth,...
	MaxBandwidth,...
	MinPhase,...
	MaxPhase,...
    MinTime,...
	MaxTime,...
	MinPsi0,...
	MaxPsi0);
end;

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%