%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% (c) 2014 Olga S. Sushkova, Alexei A. Morozov                        %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

function plot_wavelet(...
		Fig,...
		InputFileName,...
		SamplingRate,...
		SelectedChannelName,...
		Time,...
		Frequencies,...
		Power,...
		save_figures);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

Power= (abs(Power)).^2; %13-05-2021

[PathStr,ShortName,ext]= fileparts(InputFileName);

[FontName,FontSize,FontWeight]= fontAttr();

minTime= min(Time);
maxTime= max(Time);
minFreq= min(Frequencies);
maxFreq= max(Frequencies);
minPower= min(min(Power));
maxPower= max(max(Power));

figure(Fig);
set(figure(Fig),'Color',[1,1,1]);
set(figure(Fig),'NumberTitle','off');
set(figure(Fig),'name',[...
	'Signal; ',ShortName,'; ',...
	SelectedChannelName,'; ',...
	'Rate ',num2str(SamplingRate)]);
set(figure(Fig),'RendererMode','manual');
set(figure(Fig),'Renderer','zbuffer');

surf(...
	Time,...
	Frequencies,...
	Power);
shading('interp');

set(gca,'FontName',FontName);
set(gca,'FontSize',FontSize);
set(gca,'FontWeight',FontWeight);
title([	... 'Signal, ',...
	ShortName,', ',...
	SelectedChannelName,', ',...
	'Rate: ',num2str(SamplingRate)],...
	'FontName',FontName,...
	'FontSize',10,...
	'FontWeight',FontWeight,...
	'Interpreter','none');
xlabel('Time [sec]');
ylabel('Frequencies [Hz]');
zlabel('Power [mV^2/Hz]');
axis([minTime, maxTime, minFreq, maxFreq, minPower, maxPower]);
rotate3d('on');
view(0,90);
%view(0,0);

rsz_wnd(Fig);

if save_figures,
	CurrentDirectory= cd;
	FigureName1= fullfile(...
		[PathStr,'/',ShortName],...
		[...
		'Wavelet-',...
		ShortName,'-',...
		'[',...
		SelectedChannelName,...
		']']);
	cd(PathStr);
	[s,mess,messid]= mkdir(ShortName);
	save_Fig(FigureName1);
	cd(CurrentDirectory);
end;

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
