%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% (c) 2015 Olga S. Sushkova, Alexei A. Morozov                        %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

fclose('all');
close('all');
clear('all');
clc;

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

% addpath - указывает, где искать подпрограммы (функции)
% cd - возвращает полный путь текущей директории
addpath([cd,'/m']);
% \\ или / нужно поставить, указывая путь

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
Names= {...
    '/093 - PD left RS vitr E1_3 and E2_4 coherlet test envelope/',... %EMG1_EMG3 сравниваем
    '/091 - Control RS vitr E1_3 and E2_4 coherlet test envelope/'... %EMG1_EMG3 сравниваем
    };


DarkGreen= [0,0.7,0];
AlphaLevel= 0.05;
% 
CName= {...
	'EMG1'...
	};

calc_hole= true;
calc_hole= false;

% plot_roc= true;
plot_roc= false;

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
MinFreq= [1:1:5];
MaxFreq= [1:1:5];
%   
% MinFreq= 1;
% MaxFreq= 5;

%%%%%%%%%
% MinAmpl= [0:100:10000];
% MaxAmpl= [0:100:10000];
% 
MinAmpl= 0;
MaxAmpl= Inf;

%%%%%%%%%
 MinDurat= 0;
 MaxDurat= Inf;
%
% MinDurat= [0:0.1:10];
% MaxDurat= [0:0.1:10];

%%%%%%%%%
MinDurat_in_Periods= 0;
MaxDurat_in_Periods= Inf;
% 
% MinDurat_in_Periods= [0:0.1:10];
% MaxDurat_in_Periods= [0:0.1:10];

%%%%%%%%%
MinBandwidth= 0;
MaxBandwidth= Inf;
%
% MinBandwidth= [0:0.1:10];
% MaxBandwidth= [0:0.1:10];

%%%%%%%%%
MinPhase= -4;
MaxPhase= 4; 
% 
% MinPhase= [-4:0.1:4];
% MaxPhase= [-4:0.1:4]; 

%%%%%%%%%
MinTime= 0;
MaxTime= Inf;
% 
% MinTime= [0:1:90];
% MaxTime= [0:1:90];

%%%%%%%%%
MinPsi0= -4;
MaxPsi0= 4; 
%
% MinPsi0= [-4:0.3:4];
% MaxPsi0= [-4:0.3:4]; 
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%printCurrentValues= false;
printCurrentValues= true;

% plot_bar= true;
plot_bar= false;

% plot_scatters_and_set_limits= true;
plot_scatters_and_set_limits= false;

% plot_AUC_histograms= true;
plot_AUC_histograms= false;

%plot_ROC_TPR_FRR= true;
plot_ROC_TPR_FRR= false;

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

Legend= {};

AUC= zeros(...
	length(MinFreq),...
	length(MaxFreq),...
	length(MinAmpl),... 
	length(MaxAmpl),...
	length(MinDurat),...
	length(MaxDurat),...
    length(MinDurat_in_Periods),...
	length(MaxDurat_in_Periods),...
	length(MinBandwidth),...
	length(MaxBandwidth),...
	length(MinPhase),...
	length(MaxPhase),...
    length(MinTime),...
	length(MaxTime),...
	length(MinPsi0),...
	length(MaxPsi0)...
	);

AUC(:,:,:,:,:,:,:,:,:,:,:,:,:,:)= NaN;

MatrixOfFlashes= { };
TableOfNames= { };
TableOfSizes= [ ];
LengthOfFileNames2= [];

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

for q=1:length(Names),
	%
	InputFolder= [cd,Names{q}];
	%
	[...
	Matrix_of_Flash_Stack, ... 
	ListOfFileNames,...
	LengthOfFileNames,...
	LengthOfCName...
	]= load_all_people_and_channels_phase_time_psi0(InputFolder,CName);
	%
	LengthOfFileNames2= [LengthOfFileNames2;LengthOfFileNames];
	MatrixOfFlashes= [MatrixOfFlashes;Matrix_of_Flash_Stack];
	%
end;

N_Patients= LengthOfFileNames2(1);
N_Controls= LengthOfFileNames2(2);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

tab= '     ';
Clock0= clock;

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

count= 0;

AUC= nan(...
	length(MinFreq),...
	length(MaxFreq),...
	length(MinAmpl),... 
	length(MaxAmpl),...
	length(MinDurat),...
	length(MaxDurat),...
	length(MinDurat_in_Periods),...
	length(MaxDurat_in_Periods),...
	length(MinBandwidth),...
	length(MaxBandwidth),...
	length(MinPhase),...
	length(MaxPhase),...
    length(MinTime),...
	length(MaxTime),...
	length(MinPsi0),...
	length(MaxPsi0)...
);


for a=1:length(MinFreq),
	CurrentMinFreq= MinFreq(a);
	disp([...
		'CurrentMinFreq= ',...
		num2str(CurrentMinFreq)]);
	for b=1:length(MaxFreq),
		CurrentMaxFreq= MaxFreq(b);
		if printCurrentValues,
		disp([...
			tab,...
			'CurrentMaxFreq= ',...
			num2str(CurrentMaxFreq)]);
		end;
		for c=1:length(MinAmpl),
			CurrentMinAmpl= MinAmpl(c);
			if printCurrentValues,
			disp([...
				tab,tab,...
				'CurrentMinAmpl= ',...
				num2str(CurrentMinAmpl)]);
			end;
			for d=1:length(MaxAmpl),
				CurrentMaxAmpl= MaxAmpl(d);
				if printCurrentValues,
				disp([...
					tab,tab,tab,...
					'CurrentMaxAmpl= ',...
					num2str(CurrentMaxAmpl)]);
				end;
%:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::%
for e=1:length(MinDurat),
	CurrentMinDurat= MinDurat(e);
	if printCurrentValues,
	disp([...
		tab,tab,tab,tab,...
		'CurrentMinDurat= ',...
		num2str(CurrentMinDurat)]);
	end;
	for f=1:length(MaxDurat),
		CurrentMaxDurat= MaxDurat(f);
		if printCurrentValues,
		disp([...
			tab,tab,tab,tab,tab,...
			'CurrentMaxDurat= ',...
			num2str(CurrentMaxDurat)]);
		end;
        
 for g=1:length(MinDurat_in_Periods),
	CurrentMinDurat_in_Periods= MinDurat_in_Periods(g);
	if printCurrentValues,
	disp([...
		tab,tab,tab,tab,...
		'CurrentMinDurat_in_Periods= ',...
		num2str(CurrentMinDurat_in_Periods)]);
	end;
	for h=1:length(MaxDurat_in_Periods),
		CurrentMaxDurat_in_Periods= MaxDurat_in_Periods(h);
		if printCurrentValues,
		disp([...
			tab,tab,tab,tab,tab,...
			'CurrentMaxDurat_in_Periods= ',...
			num2str(CurrentMaxDurat_in_Periods)]);
		end;
        
        %%%
        
		for i=1:length(MinBandwidth),
			CurrentMinBandwidth= MinBandwidth(i);
			if printCurrentValues,
			disp([...
				tab,tab,tab,tab,tab,tab,...
				'CurrentMinBandwidth= ',...
				num2str(CurrentMinBandwidth)]);
			end;
			for j=1:length(MaxBandwidth),
				CurrentMaxBandwidth= MaxBandwidth(j);
				if printCurrentValues,
				disp([...
					tab,tab,tab,tab,tab,tab,tab,...
					'CurrentMaxBandwidth= ',...
					num2str(CurrentMaxBandwidth)]);
				end;
				
				        
		for k=1:length(MinPhase),
			CurrentMinPhase= MinPhase(k);
			if printCurrentValues,
			disp([...
				tab,tab,tab,tab,tab,tab,tab,...
				'CurrentMinPhase= ',...
				num2str(CurrentMinPhase)]);
			end;
			for l=1:length(MaxPhase),
				CurrentMaxPhase= MaxPhase(l);
				if printCurrentValues,
				disp([...
					tab,tab,tab,tab,tab,tab,tab,tab,...
					'CurrentMaxPhase= ',...
					num2str(CurrentMaxPhase)]);
				end;
                
		for m=1:length(MinTime),
			CurrentMinTime= MinTime(m);
			if printCurrentValues,
			disp([...
				tab,tab,tab,tab,tab,tab,tab,tab,...
				'CurrentMinTime= ',...
				num2str(CurrentMinTime)]);
			end;
			for n=1:length(MaxTime),
				CurrentMaxTime= MaxTime(n);
				if printCurrentValues,
				disp([...
					tab,tab,tab,tab,tab,tab,tab,tab,tab,...
					'CurrentMaxTime= ',...
					num2str(CurrentMaxTime)]);
				end;
				
		for o=1:length(MinPsi0),
			CurrentMinPsi0= MinPsi0(o);
			if printCurrentValues,
			disp([...
				tab,tab,tab,tab,tab,tab,tab,tab,tab,...
				'CurrentMinPsi0= ',...
				num2str(CurrentMinPsi0)]);
			end;
			for p=1:length(MaxPsi0),
				CurrentMaxPsi0= MaxPsi0(p);
				if printCurrentValues,
				disp([...
					tab,tab,tab,tab,tab,tab,tab,tab,tab,tab,...
					'CurrentMaxPsi0= ',...
					num2str(CurrentMaxPsi0)]);
				end;
%:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::%

count= count+1;

VectorOfQuantityOfFlashes2= [ ];
VectorOfFrequencies_Wave2= [ ]; %17-05-2021
VectorOfAmplitudes_Wave2= [ ]; %17-05-2021
VectorOfDurations_Wave2= [ ]; %17-05-2021
VectorOfDurations_in_Periods_Wave2= [ ]; %17-05-2021
VectorOfBandwidthes_Wave2= [ ]; %17-05-2021
VectorOfPhases_Wave2= [ ]; %17-05-2021
VectorOfTimes_Wave2= [ ]; %24-05-2021
VectorOfPsi0_Wave2= [ ]; %26-05-2021

for NumberOfFolder=1:length(Names),
	[...
	VectorOfQuantityOfFlashes,...
    VectorOfFrequencies_Wave,... %17-05-2021
    VectorOfAmplitudes_Wave,...%17-05-2021
    VectorOfDurations_Wave,...%17-05-2021
    VectorOfDurations_in_Periods_Wave,... %17-05-2021
    VectorOfBandwidthes_Wave,... %17-05-2021
    VectorOfPhases_Wave,... %17-05-2021
    VectorOfTimes_Wave,... %24-05-2021
	VectorOfPsi0_Wave... %26-05-2021
	]= compute_vector_of_quantities_of_flashes_phase_time_psi0(...
			CurrentMinFreq,...
			CurrentMaxFreq,...
			CurrentMinAmpl,...
			CurrentMaxAmpl,...
			CurrentMinDurat,...
			CurrentMaxDurat,...
			CurrentMinDurat_in_Periods,...
			CurrentMaxDurat_in_Periods,...
			CurrentMinBandwidth,...
			CurrentMaxBandwidth,...
			CurrentMinPhase,...
			CurrentMaxPhase,...
            CurrentMinTime,...
			CurrentMaxTime,...
			CurrentMinPsi0,...
			CurrentMaxPsi0,...
			MatrixOfFlashes,...
			N_Patients,...
			N_Controls,...
			CName,...
			NumberOfFolder,...
			LengthOfFileNames2(NumberOfFolder)...
            ); 
		%
		VectorOfQuantityOfFlashes2= ...
			[	VectorOfQuantityOfFlashes2; ...
				VectorOfQuantityOfFlashes];
        VectorOfFrequencies_Wave2= ... %17-05-2021
			[	VectorOfFrequencies_Wave2, ...
				VectorOfFrequencies_Wave];    
        VectorOfAmplitudes_Wave2= ... %17-05-2021
			[	VectorOfAmplitudes_Wave2, ...
				VectorOfAmplitudes_Wave];   
        VectorOfDurations_Wave2= ... %17-05-2021
			[	VectorOfDurations_Wave2, ...
				VectorOfDurations_Wave];   
        VectorOfDurations_in_Periods_Wave2= ... %17-05-2021
			[	VectorOfDurations_in_Periods_Wave2, ...
				VectorOfDurations_in_Periods_Wave];   
        VectorOfBandwidthes_Wave2= ... %17-05-2021
			[	VectorOfBandwidthes_Wave2, ...
				VectorOfBandwidthes_Wave];               
        VectorOfPhases_Wave2= ... %17-05-2021
			[	VectorOfPhases_Wave2, ...
				VectorOfPhases_Wave];  
        VectorOfTimes_Wave2= ... %24-05-2021
			[	VectorOfTimes_Wave2, ...
				VectorOfTimes_Wave]; 
	    VectorOfPsi0_Wave2= ... %26-05-2021
			[	VectorOfPsi0_Wave2, ...
				VectorOfPsi0_Wave]; 		
			
end;

CurrentAUC= ...
	plot_hist_quantity_of_peaks_patients_and_cont_fast_pha_t_psi0(...
	VectorOfQuantityOfFlashes2(1:N_Patients,:),...
	VectorOfQuantityOfFlashes2(N_Patients+1:end,:),...
	CurrentMinFreq,...
	CurrentMaxFreq,...
	CurrentMinAmpl,...
	CurrentMaxAmpl,...
	CurrentMinDurat,...
	CurrentMaxDurat,...
    CurrentMinDurat_in_Periods,...
    CurrentMaxDurat_in_Periods,...
	CurrentMinBandwidth,...
	CurrentMaxBandwidth,...
	CurrentMinPhase,...
	CurrentMaxPhase,...
    CurrentMinTime,...
	CurrentMaxTime,...
	CurrentMinPsi0,...
	CurrentMaxPsi0,...
	Legend,...
	plot_bar,...
	plot_AUC_histograms,...
	plot_ROC_TPR_FRR,...
    AlphaLevel,...
    DarkGreen,...
    calc_hole,...
    count);

AUC(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p)= CurrentAUC;

%:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::%
	end;
end;
%:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::%
	end;
end;
	end;
end;
%:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::%
        	end;
		end;
	end;
end;
	end;
end;
	end;
end;
	end;
end;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

save(	[...
    'Table_AUC'...
	],...
	'AUC',... 
	'MinFreq',...
	'MaxFreq',... 
	'MinAmpl',... 
	'MaxAmpl',...
	'MinDurat',...
	'MaxDurat',...
	'MinDurat_in_Periods',...
	'MaxDurat_in_Periods',...
	'MinBandwidth',...
	'MaxBandwidth',...
	'MinPhase',...
	'MaxPhase',...
    'MinTime',...
	'MaxTime',...
	'MinPsi0',...
	'MaxPsi0',...
	'Names',...
	'CName'...
	);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

Clock1= clock;

ET= etime(Clock1,Clock0);

disp(['Elapsed time: ',num2str(round(ET)),' [sec].']);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
