%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% (c) 2015 Olga S. Sushkova, Alexei A. Morozov                        %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

fclose('all');
close('all');
clear('all');
clc;

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

% addpath - указывает, где искать подпрограммы (функции)
% cd - возвращает полный путь текущей директории
addpath([cd,'/m']);
% \\ или / нужно поставить, указывая путь

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
Names= {...
    '/PD/',... %EMG1_EMG3 сравниваем
    '/Control/'... %EMG1_EMG3 сравниваем
    };


DarkGreen= [0,0.7,0];
AlphaLevel= 0.05;
% 
CName= {...
	'EMG1'...
	};

calc_hole= true;
calc_hole= false;

% plot_roc= true;
plot_roc= false;

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
MinFreq= [1:1:5];
MaxFreq= [1:1:5];
%   
% MinFreq= 1;
% MaxFreq= 5;

%%%%%%%%%
% MinAmpl= [0:10:100];
% MaxAmpl= [0:10:100];
% 
MinAmpl= 0;
MaxAmpl= Inf;

%%%%%%%%%
 MinDurat= 0;
 MaxDurat= Inf;
%
% MinDurat= [0:1:10];
% MaxDurat= [0:1:10];

%%%%%%%%%
MinDurat_in_Periods= 0;
MaxDurat_in_Periods= Inf;
% 
% % MinDurat_in_Periods= [0:1:10];
% % MaxDurat_in_Periods= [0:1:10];

%%%%%%%%%
MinBandwidth= 0;
MaxBandwidth= Inf;

% MinBandwidth= [0:1:10];
% MaxBandwidth= [0:1:10];

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%printCurrentValues= false;
printCurrentValues= true;

% plot_bar= true;
plot_bar= false;

% plot_scatters_and_set_limits= true;
plot_scatters_and_set_limits= false;

% plot_AUC_histograms= true;
plot_AUC_histograms= false;

%plot_ROC_TPR_FRR= true;
plot_ROC_TPR_FRR= false;

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

Legend= {};

AUC= zeros(...
	length(MinFreq),...
	length(MaxFreq),...
	length(MinAmpl),... 
	length(MaxAmpl),...
	length(MinDurat),...
	length(MaxDurat),...
    length(MinDurat_in_Periods),...
	length(MaxDurat_in_Periods),...
	length(MinBandwidth),...
	length(MaxBandwidth)...
	);

AUC(:,:,:,:,:,:,:,:,:,:)= NaN;

MatrixOfFlashes= { };
TableOfNames= { };
TableOfSizes= [ ];
LengthOfFileNames2= [];

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

for q=1:length(Names),
	%
	InputFolder= [cd,Names{q}];
	%
	[...
	Matrix_of_Flash_Stack, ... 
	ListOfFileNames,...
	LengthOfFileNames,...
	LengthOfCName...
	]= load_all_people_and_channels_(InputFolder,CName);
	%
	LengthOfFileNames2= [LengthOfFileNames2;LengthOfFileNames];
	MatrixOfFlashes= [MatrixOfFlashes;Matrix_of_Flash_Stack];
	%
end;

N_Patients= LengthOfFileNames2(1);
N_Controls= LengthOfFileNames2(2);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

tab= '     ';
Clock0= clock;

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

count= 0;

AUC= nan(...
	length(MinFreq),...
	length(MaxFreq),...
	length(MinAmpl),... 
	length(MaxAmpl),...
	length(MinDurat),...
	length(MaxDurat),...
	length(MinDurat_in_Periods),...
	length(MaxDurat_in_Periods),...
	length(MinBandwidth),...
	length(MaxBandwidth)...
);


for a=1:length(MinFreq),
	CurrentMinFreq= MinFreq(a);
	disp([...
		'CurrentMinFreq= ',...
		num2str(CurrentMinFreq)]);
	for b=1:length(MaxFreq),
		CurrentMaxFreq= MaxFreq(b);
		if printCurrentValues,
		disp([...
			tab,...
			'CurrentMaxFreq= ',...
			num2str(CurrentMaxFreq)]);
		end;
		for c=1:length(MinAmpl),
			CurrentMinAmpl= MinAmpl(c);
			if printCurrentValues,
			disp([...
				tab,tab,...
				'CurrentMinAmpl= ',...
				num2str(CurrentMinAmpl)]);
			end;
			for d=1:length(MaxAmpl),
				CurrentMaxAmpl= MaxAmpl(d);
				if printCurrentValues,
				disp([...
					tab,tab,tab,...
					'CurrentMaxAmpl= ',...
					num2str(CurrentMaxAmpl)]);
				end;
%:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::%
for e=1:length(MinDurat),
	CurrentMinDurat= MinDurat(e);
	if printCurrentValues,
	disp([...
		tab,tab,tab,tab,...
		'CurrentMinDurat= ',...
		num2str(CurrentMinDurat)]);
	end;
	for f=1:length(MaxDurat),
		CurrentMaxDurat= MaxDurat(f);
		if printCurrentValues,
		disp([...
			tab,tab,tab,tab,tab,...
			'CurrentMaxDurat= ',...
			num2str(CurrentMaxDurat)]);
		end;
        
 for g=1:length(MinDurat_in_Periods),
	CurrentMinDurat_in_Periods= MinDurat_in_Periods(g);
	if printCurrentValues,
	disp([...
		tab,tab,tab,tab,...
		'CurrentMinDurat_in_Periods= ',...
		num2str(CurrentMinDurat_in_Periods)]);
	end;
	for h=1:length(MaxDurat_in_Periods),
		CurrentMaxDurat_in_Periods= MaxDurat_in_Periods(h);
		if printCurrentValues,
		disp([...
			tab,tab,tab,tab,tab,...
			'CurrentMaxDurat_in_Periods= ',...
			num2str(CurrentMaxDurat_in_Periods)]);
		end;
        
        %%%
        
		for i=1:length(MinBandwidth),
			CurrentMinBandwidth= MinBandwidth(i);
			if printCurrentValues,
			disp([...
				tab,tab,tab,tab,tab,tab,...
				'CurrentMinBandwidth= ',...
				num2str(CurrentMinBandwidth)]);
			end;
			for j=1:length(MaxBandwidth),
				CurrentMaxBandwidth= MaxBandwidth(j);
				if printCurrentValues,
				disp([...
					tab,tab,tab,tab,tab,tab,tab,...
					'CurrentMaxBandwidth= ',...
					num2str(CurrentMaxBandwidth)]);
				end;
				
				        
%:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::%

count= count+1;

VectorOfQuantityOfFlashes2= [ ];
VectorOfFrequencies_Wave2= [ ]; %17-05-2021
VectorOfAmplitudes_Wave2= [ ]; %17-05-2021
VectorOfDurations_Wave2= [ ]; %17-05-2021
VectorOfDurations_in_Periods_Wave2= [ ]; %17-05-2021
VectorOfBandwidthes_Wave2= [ ]; %17-05-2021

for NumberOfFolder=1:length(Names),
	[...
	VectorOfQuantityOfFlashes,...
    VectorOfFrequencies_Wave,... %17-05-2021
    VectorOfAmplitudes_Wave,...%17-05-2021
    VectorOfDurations_Wave,...%17-05-2021
    VectorOfDurations_in_Periods_Wave,... %17-05-2021
    VectorOfBandwidthes_Wave... %17-05-2021
	]= compute_vector_of_quantities_of_flashes_(...
			CurrentMinFreq,...
			CurrentMaxFreq,...
			CurrentMinAmpl,...
			CurrentMaxAmpl,...
			CurrentMinDurat,...
			CurrentMaxDurat,...
			CurrentMinDurat_in_Periods,...
			CurrentMaxDurat_in_Periods,...
			CurrentMinBandwidth,...
			CurrentMaxBandwidth,...
			MatrixOfFlashes,...
			N_Patients,...
			N_Controls,...
			CName,...
			NumberOfFolder,...
			LengthOfFileNames2(NumberOfFolder)...
            ); 
		%
		VectorOfQuantityOfFlashes2= ...
			[	VectorOfQuantityOfFlashes2; ...
				VectorOfQuantityOfFlashes];
        VectorOfFrequencies_Wave2= ... %17-05-2021
			[	VectorOfFrequencies_Wave2, ...
				VectorOfFrequencies_Wave];    
        VectorOfAmplitudes_Wave2= ... %17-05-2021
			[	VectorOfAmplitudes_Wave2, ...
				VectorOfAmplitudes_Wave];   
        VectorOfDurations_Wave2= ... %17-05-2021
			[	VectorOfDurations_Wave2, ...
				VectorOfDurations_Wave];   
        VectorOfDurations_in_Periods_Wave2= ... %17-05-2021
			[	VectorOfDurations_in_Periods_Wave2, ...
				VectorOfDurations_in_Periods_Wave];   
        VectorOfBandwidthes_Wave2= ... %17-05-2021
			[	VectorOfBandwidthes_Wave2, ...
				VectorOfBandwidthes_Wave];               
			
end;

CurrentAUC= ...
	plot_hist_quantity_of_peaks_patients_and_cont_fast_(...
	VectorOfQuantityOfFlashes2(1:N_Patients,:),...
	VectorOfQuantityOfFlashes2(N_Patients+1:end,:),...
	CurrentMinFreq,...
	CurrentMaxFreq,...
	CurrentMinAmpl,...
	CurrentMaxAmpl,...
	CurrentMinDurat,...
	CurrentMaxDurat,...
    CurrentMinDurat_in_Periods,...
    CurrentMaxDurat_in_Periods,...
	CurrentMinBandwidth,...
	CurrentMaxBandwidth,...
	Legend,...
	plot_bar,...
	plot_AUC_histograms,...
	plot_ROC_TPR_FRR,...
    AlphaLevel,...
    DarkGreen,...
    calc_hole,...
    count);

AUC(a,b,c,d,e,f,g,h,i,j)= CurrentAUC;

%:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::%
	end;
end;
%:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::%
	end;
end;
	end;
end;
%:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::%
        	end;
		end;
	end;
end;

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

save(	[...
    'Table_AUC'...
	],...
	'AUC',... 
	'MinFreq',...
	'MaxFreq',... 
	'MinAmpl',... 
	'MaxAmpl',...
	'MinDurat',...
	'MaxDurat',...
	'MinDurat_in_Periods',...
	'MaxDurat_in_Periods',...
	'MinBandwidth',...
	'MaxBandwidth',...
	'Names',...
	'CName'...
	);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

Clock1= clock;

ET= etime(Clock1,Clock0);

disp(['Elapsed time: ',num2str(round(ET)),' [sec].']);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
