%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% (c) 2015 Olga S. Sushkova, Alexei A. Morozov                       %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
fclose('all');
close('all');
clear('all');
rehash;
clc;
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
% addpath - указывает, где искать подпрограммы (функции)
% cd - возвращает полный путь текущей директории
addpath([cd,'/m']);
% \\ или / нужно поставить, указывая путь
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
InputFolder= [cd,'/Control/']; 
%InputFolder= [cd,'/PD/'];

%Method= 'FFT';
Method= 'COMPLEX_MORLET';

if strcmp(Method,'COMPLEX_MORLET'),
	ListOfMetrics= {...
		'AVERAGE',... это
		'MEDIAN',...
		'SIGMA',...
		'FLASH_POWER_AVERAGE',... это
		'FLASH_POWER_MEDIAN',...
		'FLASH_POWER_SIGMA',... +это
		'FLASHES_PER_SEC',... это
		'FLASH_FREQUENCY_AVERAGE',... это
		'FLASH_FREQUENCY_MEDIAN',...
		'FLASH_FREQUENCY_SIGMA',... это
		'FLASH_DURATION_AVERAGE',... это
		'FLASH_DURATION_MEDIAN',...
		'FLASH_DURATION_SIGMA',... это
		'FLASH_PERIOD_QUANTITY_AVERAGE',... это
		'FLASH_PERIOD_QUANTITY_MEDIAN',...
		'FLASH_PERIOD_QUANTITY_SIGMA',... это
		'FLASH_BANDWIDTH_AVERAGE'... это
		'FLASH_BANDWIDTH_MEDIAN',...
		'FLASH_BANDWIDTH_SIGMA',...
		'FLASH_SUMM_OF_DURATIONS'...
		};
	ListOfMetrics= {...
		'FLASHES_PER_SEC',...
		};
else
	ListOfMetrics= {...
		'AVERAGE',... это
		'MAXIMUM',... это
		'FREQUENCY',... это
		'MEDIAN'... это
		...'AVERAGE_div_MEDIAN',...
		...'MAXIMUM_div_MEDIAN'...
		...'HIST_AVERAGE',...
		...'HIST_MAXIMUM',...
		...'HIST_FREQUENCY',...
		...'HIST_MEDIAN',...
		...'HIST_AVERAGE_div_MEDIAN',...
		...'HIST_MAXIMUM_div_MEDIAN'...
		};
end;

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

ArrayOfLowerAndUpperBounds= [...
	4, 8; ...	% Theta
	8, 12; ...	% Alpha
	12, 24; ...	% Beta
	24, 48 ...	% Gamma
	];
ArrayOfRangeNames= {...
	'Theta', ...
	'Alpha', ...
	'Beta', ...
	'Gamma'};

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

plot_signals= false;
%plot_signals= true;

if strcmp(Method,'FFT'),
	calc_spectra= true;
else
	calc_spectra= false;
end;

plot_spectra= false;
% plot_spectra= true;

if strcmp(Method,'COMPLEX_MORLET'),
	calc_wavelets= true;
else
	calc_wavelets= false;
end;

plot_wavelets= false;
%plot_wavelets= true;

plot_flash_diagrams= false;
%plot_flash_diagrams= true;

save_figures= false;
% save_figures= true;

%save_flash_diagrams= false;
save_flash_diagrams= true;

save_wavelet_matrices= false;
%save_wavelet_matrices= true;

calc_histograms= false;
%calc_histograms= true;

eliminate_beta= false;
%eliminate_beta= true;

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

ViborHist= 'simple';
% ViborHist= 'summa';
% ViborHist= 'standard';

plot_histograms= false;
% plot_histograms= true;

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

SamplingRate0= 500; % Частота дискретизации

X84_WindowLengthInMinutes= 1; % [minutes]

 %DecimationFactor= 1;
 DecimationFactor= 4; %acs-beta 
 %DecimationFactor= 20; %acs-delta 

Low_Freq= 0.1; % Порог нижнего значения частоты (НЕ на графиках)

Step_Freq= 0.1; % Шаг по частоте для вычисления вейвлетов

Upper_Freq= 50; % Порог верхнего значения частоты (НЕ на графиках)

% Этот параметр является половиной минимально допустимой полной
% ширины вспышки (по частоте).
% Это - ограничение на ширину вспышки вцелом!
ThresholdOfHalfOfFullWidthOfFrequencyInHz= 0.0; % Гц

% Этот параметр является минимально допустимой полушириной
% вспышки (по частоте), как справа, так и слева.
% Это - ограничение на длину хвостиков вспышки!
threshold_of_half_width_of_frequency_in_Hz= 0.0; % Гц

Number_of_periods= 0.1; % Число периодов (2019-02-28)

RequestedWindowLength= 3; % Длина окна при вычислении спектра
TrailingZerosIntervalLength= 100; % Параметр сглаживания спектра
SpectraWindowOverlap= '7 / 8'; % Размер перекрытия окна

MinFreq= 2; % Минимальная частота (для графиков)

MaxFreq= 48; % Максимальная частота (для графиков)

Fb= 1; % Параметр для вычисления вейвлетов
Fc= 1; % Параметр для вычисления вейвлетов

NotchFilterQ= 35; % Параметр режекторного фильтра (добротность)

Kol_stolb= 25;

% Check_Amplitude_Values= true;
Check_Amplitude_Values= false;

Minimal_Amplitude_Value_for_auc= 1;

% Maximal_Amplitude_Value_for_auc= 50;
Maximal_Amplitude_Value_for_auc= 130;

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

Clock0= clock;

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

ChannelNames= {...
	'FP1',...
	'FP2',...
	'F3',...
	'F4',...
	'C3',...
	'C4',...
	'P3',...
	'P4',...
	'O1',...
	'O2',...
	'F7',...
	'F8',...
	'T3',...
	'T4',...
	'T5',...
	'T6',...
	'CZ',...
	'EMG1',...
	'EMG2',...
	'EMG3',...
	'EMG4',...
	'X2',...
	'X4',...
	'X6',...
	'X8'...
	};

ChannelNamesSelectedByUser= {...
	'EMG1'};

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

for i=1:length(ListOfMetrics),
        CurrentMetrics= ListOfMetrics{i};
	group2mat(...
		InputFolder,...
		ChannelNames,...
		ChannelNamesSelectedByUser,...
		Method,...
		CurrentMetrics,...
		ArrayOfLowerAndUpperBounds,...
		ArrayOfRangeNames,...
		SamplingRate0,...
		X84_WindowLengthInMinutes,...
		NotchFilterQ,...
		DecimationFactor,...
		RequestedWindowLength,...
		TrailingZerosIntervalLength,...
		SpectraWindowOverlap,...
		Low_Freq,...
		Step_Freq,...
		Upper_Freq,...
		Fb,...
		Fc,...
		ThresholdOfHalfOfFullWidthOfFrequencyInHz,...
		threshold_of_half_width_of_frequency_in_Hz,...
		Number_of_periods,...
		plot_signals,...
		calc_spectra,...
		plot_spectra,...
		calc_wavelets,...
		plot_wavelets,...
		plot_flash_diagrams,...
		save_flash_diagrams,...
		save_wavelet_matrices,...
		Kol_stolb,...
		calc_histograms,...
		ViborHist,...
		plot_histograms,...
		save_figures,...
		MinFreq,...
		MaxFreq,...
		Minimal_Amplitude_Value_for_auc,...
		Maximal_Amplitude_Value_for_auc,...
		Check_Amplitude_Values,...
        eliminate_beta);
end;

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

Clock1= clock;

ET= etime(Clock1,Clock0);

disp(['Elapsed time: ',num2str(round(ET)),' [sec].']);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
