%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% (c) 2015 Olga S. Sushkova, Alexei A. Morozov                       %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
fclose('all');
close('all');
clear('all');
rehash;
clc;
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
% addpath - óêàçûâàåò, ãäå èñêàòü ïîäïðîãðàììû (ôóíêöèè)
% cd - âîçâðàùàåò ïîëíûé ïóòü òåêóùåé äèðåêòîðèè
addpath([cd,'/m']);
% \\ èëè / íóæíî ïîñòàâèòü, óêàçûâàÿ ïóòü
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
InputFolder= [cd,'/Control/']; 
%InputFolder= [cd,'/PD/'];

%Method= 'FFT';
Method= 'COMPLEX_MORLET';

if strcmp(Method,'COMPLEX_MORLET'),
	ListOfMetrics= {...
		'AVERAGE',... ýòî
		'MEDIAN',...
		'SIGMA',...
		'FLASH_POWER_AVERAGE',... ýòî
		'FLASH_POWER_MEDIAN',...
		'FLASH_POWER_SIGMA',... +ýòî
		'FLASHES_PER_SEC',... ýòî
		'FLASH_FREQUENCY_AVERAGE',... ýòî
		'FLASH_FREQUENCY_MEDIAN',...
		'FLASH_FREQUENCY_SIGMA',... ýòî
		'FLASH_DURATION_AVERAGE',... ýòî
		'FLASH_DURATION_MEDIAN',...
		'FLASH_DURATION_SIGMA',... ýòî
		'FLASH_PERIOD_QUANTITY_AVERAGE',... ýòî
		'FLASH_PERIOD_QUANTITY_MEDIAN',...
		'FLASH_PERIOD_QUANTITY_SIGMA',... ýòî
		'FLASH_BANDWIDTH_AVERAGE'... ýòî
		'FLASH_BANDWIDTH_MEDIAN',...
		'FLASH_BANDWIDTH_SIGMA',...
		'FLASH_SUMM_OF_DURATIONS'...
		};
	ListOfMetrics= {...
		'FLASHES_PER_SEC',...
		};
else
	ListOfMetrics= {...
		'AVERAGE',... ýòî
		'MAXIMUM',... ýòî
		'FREQUENCY',... ýòî
		'MEDIAN'... ýòî
		...'AVERAGE_div_MEDIAN',...
		...'MAXIMUM_div_MEDIAN'...
		...'HIST_AVERAGE',...
		...'HIST_MAXIMUM',...
		...'HIST_FREQUENCY',...
		...'HIST_MEDIAN',...
		...'HIST_AVERAGE_div_MEDIAN',...
		...'HIST_MAXIMUM_div_MEDIAN'...
		};
end;

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

ArrayOfLowerAndUpperBounds= [...
	4, 8; ...	% Theta
	8, 12; ...	% Alpha
	12, 24; ...	% Beta
	24, 48 ...	% Gamma
	];
ArrayOfRangeNames= {...
	'Theta', ...
	'Alpha', ...
	'Beta', ...
	'Gamma'};

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

plot_signals= false;
%plot_signals= true;

if strcmp(Method,'FFT'),
	calc_spectra= true;
else
	calc_spectra= false;
end;

plot_spectra= false;
% plot_spectra= true;

if strcmp(Method,'COMPLEX_MORLET'),
	calc_wavelets= true;
else
	calc_wavelets= false;
end;

plot_wavelets= false;
%plot_wavelets= true;

plot_flash_diagrams= false;
%plot_flash_diagrams= true;

save_figures= false;
% save_figures= true;

 save_flash_diagrams= false;
%save_flash_diagrams= true;

save_wavelet_matrices= false;
save_wavelet_matrices= true;

calc_histograms= false;
%calc_histograms= true;

eliminate_beta= false;
%eliminate_beta= true;

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

ViborHist= 'simple';
% ViborHist= 'summa';
% ViborHist= 'standard';

plot_histograms= false;
% plot_histograms= true;

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

SamplingRate0= 500; % ×àñòîòà äèñêðåòèçàöèè

X84_WindowLengthInMinutes= 1; % [minutes]

 %DecimationFactor= 1;
 DecimationFactor= 4; %acs-beta 
 %DecimationFactor= 20; %acs-delta 

Low_Freq= 0.1; % Ïîðîã íèæíåãî çíà÷åíèÿ ÷àñòîòû (ÍÅ íà ãðàôèêàõ)

Step_Freq= 0.1; % Øàã ïî ÷àñòîòå äëÿ âû÷èñëåíèÿ âåéâëåòîâ

Upper_Freq= 50; % Ïîðîã âåðõíåãî çíà÷åíèÿ ÷àñòîòû (ÍÅ íà ãðàôèêàõ)

% Ýòîò ïàðàìåòð ÿâëÿåòñÿ ïîëîâèíîé ìèíèìàëüíî äîïóñòèìîé ïîëíîé
% øèðèíû âñïûøêè (ïî ÷àñòîòå).
% Ýòî - îãðàíè÷åíèå íà øèðèíó âñïûøêè âöåëîì!
ThresholdOfHalfOfFullWidthOfFrequencyInHz= 0.0; % Ãö

% Ýòîò ïàðàìåòð ÿâëÿåòñÿ ìèíèìàëüíî äîïóñòèìîé ïîëóøèðèíîé
% âñïûøêè (ïî ÷àñòîòå), êàê ñïðàâà, òàê è ñëåâà.
% Ýòî - îãðàíè÷åíèå íà äëèíó õâîñòèêîâ âñïûøêè!
threshold_of_half_width_of_frequency_in_Hz= 0.0; % Ãö

Number_of_periods= 0.1; % ×èñëî ïåðèîäîâ (2019-02-28)

RequestedWindowLength= 3; % Äëèíà îêíà ïðè âû÷èñëåíèè ñïåêòðà
TrailingZerosIntervalLength= 100; % Ïàðàìåòð ñãëàæèâàíèÿ ñïåêòðà
SpectraWindowOverlap= '7 / 8'; % Ðàçìåð ïåðåêðûòèÿ îêíà

MinFreq= 2; % Ìèíèìàëüíàÿ ÷àñòîòà (äëÿ ãðàôèêîâ)

MaxFreq= 48; % Ìàêñèìàëüíàÿ ÷àñòîòà (äëÿ ãðàôèêîâ)

Fb= 1; % Ïàðàìåòð äëÿ âû÷èñëåíèÿ âåéâëåòîâ
Fc= 1; % Ïàðàìåòð äëÿ âû÷èñëåíèÿ âåéâëåòîâ

NotchFilterQ= 35; % Ïàðàìåòð ðåæåêòîðíîãî ôèëüòðà (äîáðîòíîñòü)

Kol_stolb= 25;

% Check_Amplitude_Values= true;
Check_Amplitude_Values= false;

Minimal_Amplitude_Value_for_auc= 1;

% Maximal_Amplitude_Value_for_auc= 50;
Maximal_Amplitude_Value_for_auc= 130;

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

Clock0= clock;

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

ChannelNames= {...
	'FP1',...
	'FP2',...
	'F3',...
	'F4',...
	'C3',...
	'C4',...
	'P3',...
	'P4',...
	'O1',...
	'O2',...
	'F7',...
	'F8',...
	'T3',...
	'T4',...
	'T5',...
	'T6',...
	'CZ',...
	'EMG1',...
	'EMG2',...
	'EMG3',...
	'EMG4',...
	'X2',...
	'X4',...
	'X6',...
	'X8'...
	};

ChannelNamesSelectedByUser= {...
	'EMG1'};

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

for i=1:length(ListOfMetrics),
        CurrentMetrics= ListOfMetrics{i};
	group2mat(...
		InputFolder,...
		ChannelNames,...
		ChannelNamesSelectedByUser,...
		Method,...
		CurrentMetrics,...
		ArrayOfLowerAndUpperBounds,...
		ArrayOfRangeNames,...
		SamplingRate0,...
		X84_WindowLengthInMinutes,...
		NotchFilterQ,...
		DecimationFactor,...
		RequestedWindowLength,...
		TrailingZerosIntervalLength,...
		SpectraWindowOverlap,...
		Low_Freq,...
		Step_Freq,...
		Upper_Freq,...
		Fb,...
		Fc,...
		ThresholdOfHalfOfFullWidthOfFrequencyInHz,...
		threshold_of_half_width_of_frequency_in_Hz,...
		Number_of_periods,...
		plot_signals,...
		calc_spectra,...
		plot_spectra,...
		calc_wavelets,...
		plot_wavelets,...
		plot_flash_diagrams,...
		save_flash_diagrams,...
		save_wavelet_matrices,...
		Kol_stolb,...
		calc_histograms,...
		ViborHist,...
		plot_histograms,...
		save_figures,...
		MinFreq,...
		MaxFreq,...
		Minimal_Amplitude_Value_for_auc,...
		Maximal_Amplitude_Value_for_auc,...
		Check_Amplitude_Values,...
        eliminate_beta);
end;

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

Clock1= clock;

ET= etime(Clock1,Clock0);

disp(['Elapsed time: ',num2str(round(ET)),' [sec].']);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
